# Generated by Django 4.2.16 on 2024-10-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
