# Generated by Django 4.2.16 on 2024-10-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0003_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
