# Generated by Django 4.2.16 on 2024-10-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0004_remove_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
