# Generated by Django 4.2.16 on 2024-10-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
