# Generated by Django 4.2.16 on 2024-10-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0011_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
